/*
 * Copyright (c) 2017 TDK Invensense
 *
 * SPDX-License-Identifier: BSD 3-Clause
 */

#ifndef _INV_IMU_DEFS_INTERNAL_H_
#define _INV_IMU_DEFS_INTERNAL_H_

#ifdef __cplusplus
extern "C" {
#endif

/** @file inv_imu_defs_internal.h
 * File exposing the device register map
 */

#include <stdint.h>

#include "icm566xx/imu/inv_imu_defs.h"

/* Include regmap internal (le = little endian, be = big endian) */
#include "icm566xx/imu/inv_imu_regmap_internal_le.h"
/* #include "icm566xx/imu/inv_imu_regmap_internal_be.h" */

/* Manufacturing info */
#define OTP_MANUFACT_INFO_ADDR 0xAAF3
#define OTP_MANUFACT_INFO_SIZE 8

/*/* */
*--*DMD_GCT_TRIM1_B3 * --*Register Name: DMD_GCT_TRIM1 * --* /
#if defined(DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS)
#error "check DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS definition and remove this message"
#else
/*#warning "DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS not defined in Xian regmap yet. Use coronado
 * definition temporarily" */
#define DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS  0x02
#define DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_MASK (0x07 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS)
#endif
	typedef enum {
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_128KHZ =
		(0x6 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_64KHZ =
		(0x5 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_32KHZ =
		(0x4 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_16KHZ =
		(0x3 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_8KHZ =
		(0x2 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_4KHZ =
		(0x1 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS),
	DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_DIS = (0x0 << DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_POS)
} DMD_GCT_TRIM1_GYRO_ADC_CHOP_TRIM_D2A_t;

/*/* */
*--*ACCEL_XY_TRIM1_B3 * --*Register Name: ACCEL_XY_TRIM1 * --* /
#if defined(ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS)
#error "check ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS definition and remove this message"
#else
/*#warning "ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS not defined in Xian regmap yet. Use
 * coronado definition temporarily" */
#define ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS  0x00
#define ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_MASK 0x07
#endif
	typedef enum {
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_128KHZ =
		(0x6 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_64KHZ =
		(0x5 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_32KHZ =
		(0x4 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_16KHZ =
		(0x3 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_8KHZ =
		(0x2 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_4KHZ =
		(0x1 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS),
	ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_DIS =
		(0x0 << ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_POS)
} ACCEL_XY_TRIM1_ACCEL_ADC_CHOP_RATE_TRIM_D2A_t;

/*
 * IREG_OTP_CFG
 * Register Name: IREG_OTP_CFG
 */
typedef enum {
	IREG_OTP_CFG_OTP_COPY_TRIM = 1,
	IREG_OTP_CFG_OTP_COPY_ST_DATA = 3,
} OTP_CONFIG_COPY_MODE_t;

typedef enum {
	INV_IMU_16_BIT_DATA,
	INV_IMU_20_BIT_DATA
} inv_imu_sensor_reg_len_t;

#ifdef __cplusplus
}
#endif

#endif /* #ifndef _INV_IMU_DEFS_INTERNAL_H_ */
